// Adder 0

export const TOGGLE_VAR_A_ADDER_0 = 'TOGGLE_VAR_A_ADDER_0';
export const TOGGLE_VAR_B_ADDER_0 = 'TOGGLE_VAR_B_ADDER_0';
export const SET_TRANSFER_ADDER_0 = 'SET_TRANSFER_ADDER_0';
export const SET_INPUT_TRANSFER_ADDER_0 = 'SET_INPUT_TRANSFER_ADDER_0';
export const SET_SUMM_ADDER_0 = 'SET_SUMM_ADDER_0';

// Adder 1

export const TOGGLE_VAR_A_ADDER_1 = 'TOGGLE_VAR_A_ADDER_1';
export const TOGGLE_VAR_B_ADDER_1 = 'TOGGLE_VAR_B_ADDER_1';
export const SET_TRANSFER_ADDER_1 = 'SET_TRANSFER_ADDER_1';
export const SET_INPUT_TRANSFER_ADDER_1 = 'SET_INPUT_TRANSFER_ADDER_1';
export const SET_SUMM_ADDER_1 = 'SET_SUMM_ADDER_1';

// Adder 2

export const TOGGLE_VAR_A_ADDER_2 = 'TOGGLE_VAR_A_ADDER_2';
export const TOGGLE_VAR_B_ADDER_2 = 'TOGGLE_VAR_B_ADDER_2';
export const SET_TRANSFER_ADDER_2 = 'SET_TRANSFER_ADDER_2';
export const SET_INPUT_TRANSFER_ADDER_2 = 'SET_INPUT_TRANSFER_ADDER_2';
export const SET_SUMM_ADDER_2 = 'SET_SUMM_ADDER_2';

// Adder 3

export const TOGGLE_VAR_A_ADDER_3 = 'TOGGLE_VAR_A_ADDER_3';
export const TOGGLE_VAR_B_ADDER_3 = 'TOGGLE_VAR_B_ADDER_3';
export const SET_TRANSFER_ADDER_3 = 'SET_TRANSFER_ADDER_3';
export const SET_INPUT_TRANSFER_ADDER_3 = 'SET_INPUT_TRANSFER_ADDER_3';
export const SET_SUMM_ADDER_3 = 'SET_SUMM_ADDER_3';

// Adder 4

export const TOGGLE_VAR_A_ADDER_4 = 'TOGGLE_VAR_A_ADDER_4';
export const TOGGLE_VAR_B_ADDER_4 = 'TOGGLE_VAR_B_ADDER_4';
export const SET_TRANSFER_ADDER_4 = 'SET_TRANSFER_ADDER_4';
export const SET_INPUT_TRANSFER_ADDER_4 = 'SET_INPUT_TRANSFER_ADDER_4';
export const SET_SUMM_ADDER_4 = 'SET_SUMM_ADDER_4';

// Adder 5

export const TOGGLE_VAR_A_ADDER_5 = 'TOGGLE_VAR_A_ADDER_5';
export const TOGGLE_VAR_B_ADDER_5 = 'TOGGLE_VAR_B_ADDER_5';
export const SET_TRANSFER_ADDER_5 = 'SET_TRANSFER_ADDER_5';
export const SET_INPUT_TRANSFER_ADDER_5 = 'SET_INPUT_TRANSFER_ADDER_5';
export const SET_SUMM_ADDER_5 = 'SET_SUMM_ADDER_5';

// Adder 6

export const TOGGLE_VAR_A_ADDER_6 = 'TOGGLE_VAR_A_ADDER_6';
export const TOGGLE_VAR_B_ADDER_6 = 'TOGGLE_VAR_B_ADDER_6';
export const SET_TRANSFER_ADDER_6 = 'SET_TRANSFER_ADDER_6';
export const SET_INPUT_TRANSFER_ADDER_6 = 'SET_INPUT_TRANSFER_ADDER_6';
export const SET_SUMM_ADDER_6 = 'SET_SUMM_ADDER_6';

// Adder 7

export const TOGGLE_VAR_A_ADDER_7 = 'TOGGLE_VAR_A_ADDER_7';
export const TOGGLE_VAR_B_ADDER_7 = 'TOGGLE_VAR_B_ADDER_7';
export const SET_TRANSFER_ADDER_7 = 'SET_TRANSFER_ADDER_7';
export const SET_INPUT_TRANSFER_ADDER_7 = 'SET_INPUT_TRANSFER_ADDER_7';
export const SET_SUMM_ADDER_7 = 'SET_SUMM_ADDER_7';
