export const USER_NAME = 'USER_NAME'
export const EMAIL = 'EMAIL'
export const PHONE_NUMBER = 'PHONE_NUMBER'
export const SCIENCE_DEGREE = 'SCIENCE_DEGREE'
export const UNIVERSITY = 'UNIVERSITY'
export const FETCH_TEACHER = 'FETCH_TEACHER'
export const REDIRECT_HOME = 'REDIRECT_HOME'
