// Register
export const CHANGE_REGISTER_STATE = 'CHANGE_REGISTER_STATE';
// Adder
export const CHANGE_ADDER_STATE = 'CHANGE_ADDER_STATE';
// Operations value
export const CHANGE_OPERATION_VALUE = 'CHANGE_OPERATION_VALUE';
