// Register A
export const TOGGLE_REGISTER_A_V0 = 'TOGGLE_REGISTER_A_V0';
export const TOGGLE_REGISTER_A_V1 = 'TOGGLE_REGISTER_A_V1';
export const TOGGLE_REGISTER_A_D = 'TOGGLE_REGISTER_A_D';
export const TOGGLE_REGISTER_A_VAR_0 = 'TOGGLE_REGISTER_A_VAR_0';
export const TOGGLE_REGISTER_A_VAR_1 = 'TOGGLE_REGISTER_A_VAR_1';
export const TOGGLE_REGISTER_A_VAR_2 = 'TOGGLE_REGISTER_A_VAR_2';
export const TOGGLE_REGISTER_A_VAR_3 = 'TOGGLE_REGISTER_A_VAR_3';
export const TOGGLE_REGISTER_A_VAR_4 = 'TOGGLE_REGISTER_A_VAR_4';
export const TOGGLE_REGISTER_A_VAR_5 = 'TOGGLE_REGISTER_A_VAR_5';
export const TOGGLE_REGISTER_A_VAR_6 = 'TOGGLE_REGISTER_A_VAR_6';
export const TOGGLE_REGISTER_A_VAR_7 = 'TOGGLE_REGISTER_A_VAR_7';
// Register B
export const TOGGLE_REGISTER_B_V0 = 'TOGGLE_REGISTER_B_V0';
export const TOGGLE_REGISTER_B_V1 = 'TOGGLE_REGISTER_B_V1';
export const TOGGLE_REGISTER_B_D = 'TOGGLE_REGISTER_B_D';
export const TOGGLE_REGISTER_B_VAR_0 = 'TOGGLE_REGISTER_B_VAR_0';
export const TOGGLE_REGISTER_B_VAR_1 = 'TOGGLE_REGISTER_B_VAR_1';
export const TOGGLE_REGISTER_B_VAR_2 = 'TOGGLE_REGISTER_B_VAR_2';
export const TOGGLE_REGISTER_B_VAR_3 = 'TOGGLE_REGISTER_B_VAR_3';
export const TOGGLE_REGISTER_B_VAR_4 = 'TOGGLE_REGISTER_B_VAR_4';
export const TOGGLE_REGISTER_B_VAR_5 = 'TOGGLE_REGISTER_B_VAR_5';
export const TOGGLE_REGISTER_B_VAR_6 = 'TOGGLE_REGISTER_B_VAR_6';
export const TOGGLE_REGISTER_B_VAR_7 = 'TOGGLE_REGISTER_B_VAR_7';
// Register C
export const TOGGLE_REGISTER_C_V0 = 'TOGGLE_REGISTER_C_V0';
export const TOGGLE_REGISTER_C_V1 = 'TOGGLE_REGISTER_C_V1';
export const TOGGLE_REGISTER_C_D = 'TOGGLE_REGISTER_C_D';
export const TOGGLE_REGISTER_C_VAR_0 = 'TOGGLE_REGISTER_C_VAR_0';
export const TOGGLE_REGISTER_C_VAR_1 = 'TOGGLE_REGISTER_C_VAR_1';
export const TOGGLE_REGISTER_C_VAR_2 = 'TOGGLE_REGISTER_C_VAR_2';
export const TOGGLE_REGISTER_C_VAR_3 = 'TOGGLE_REGISTER_C_VAR_3';
export const TOGGLE_REGISTER_C_VAR_4 = 'TOGGLE_REGISTER_C_VAR_4';
export const TOGGLE_REGISTER_C_VAR_5 = 'TOGGLE_REGISTER_C_VAR_5';
export const TOGGLE_REGISTER_C_VAR_6 = 'TOGGLE_REGISTER_C_VAR_6';
export const TOGGLE_REGISTER_C_VAR_7 = 'TOGGLE_REGISTER_C_VAR_7';
// Adder 0
export const TOGGLE_ADDER_0_INPUT_B = 'TOGGLE_ADDER_0_INPUT_B';
export const TOGGLE_ADDER_0_INPUT_B = 'TOGGLE_ADDER_0_INPUT_B';
export const TOGGLE_ADDER_0_INPUT_B = 'TOGGLE_ADDER_0_INPUT_B';
export const TOGGLE_ADDER_0_OUTPUT_S = 'TOGGLE_ADDER_0_OUTPUT_S';
export const TOGGLE_ADDER_0_OUTPUT_S = 'TOGGLE_ADDER_0_OUTPUT_S';
// Adder 1
export const TOGGLE_ADDER_1_INPUT_B = 'TOGGLE_ADDER_1_INPUT_B';
export const TOGGLE_ADDER_1_INPUT_B = 'TOGGLE_ADDER_1_INPUT_B';
export const TOGGLE_ADDER_1_INPUT_B = 'TOGGLE_ADDER_1_INPUT_B';
export const TOGGLE_ADDER_1_OUTPUT_S = 'TOGGLE_ADDER_1_OUTPUT_S';
export const TOGGLE_ADDER_1_OUTPUT_S = 'TOGGLE_ADDER_1_OUTPUT_S';
// Adder 2
export const TOGGLE_ADDER_2_INPUT_B = 'TOGGLE_ADDER_2_INPUT_B';
export const TOGGLE_ADDER_2_INPUT_B = 'TOGGLE_ADDER_2_INPUT_B';
export const TOGGLE_ADDER_2_INPUT_B = 'TOGGLE_ADDER_2_INPUT_B';
export const TOGGLE_ADDER_2_OUTPUT_S = 'TOGGLE_ADDER_2_OUTPUT_S';
export const TOGGLE_ADDER_2_OUTPUT_S = 'TOGGLE_ADDER_2_OUTPUT_S';
// Adder 3
export const TOGGLE_ADDER_3_INPUT_B = 'TOGGLE_ADDER_3_INPUT_B';
export const TOGGLE_ADDER_3_INPUT_B = 'TOGGLE_ADDER_3_INPUT_B';
export const TOGGLE_ADDER_3_INPUT_B = 'TOGGLE_ADDER_3_INPUT_B';
export const TOGGLE_ADDER_3_OUTPUT_S = 'TOGGLE_ADDER_3_OUTPUT_S';
export const TOGGLE_ADDER_3_OUTPUT_S = 'TOGGLE_ADDER_3_OUTPUT_S';
// Adder 4
export const TOGGLE_ADDER_4_INPUT_B = 'TOGGLE_ADDER_4_INPUT_B';
export const TOGGLE_ADDER_4_INPUT_B = 'TOGGLE_ADDER_4_INPUT_B';
export const TOGGLE_ADDER_4_INPUT_B = 'TOGGLE_ADDER_4_INPUT_B';
export const TOGGLE_ADDER_4_OUTPUT_S = 'TOGGLE_ADDER_4_OUTPUT_S';
export const TOGGLE_ADDER_4_OUTPUT_S = 'TOGGLE_ADDER_4_OUTPUT_S';
// Adder 5
export const TOGGLE_ADDER_5_INPUT_B = 'TOGGLE_ADDER_5_INPUT_B';
export const TOGGLE_ADDER_5_INPUT_B = 'TOGGLE_ADDER_5_INPUT_B';
export const TOGGLE_ADDER_5_INPUT_B = 'TOGGLE_ADDER_5_INPUT_B';
export const TOGGLE_ADDER_5_OUTPUT_S = 'TOGGLE_ADDER_5_OUTPUT_S';
export const TOGGLE_ADDER_5_OUTPUT_S = 'TOGGLE_ADDER_5_OUTPUT_S';
// Adder 6
export const TOGGLE_ADDER_6_INPUT_B = 'TOGGLE_ADDER_6_INPUT_B';
export const TOGGLE_ADDER_6_INPUT_B = 'TOGGLE_ADDER_6_INPUT_B';
export const TOGGLE_ADDER_6_INPUT_B = 'TOGGLE_ADDER_6_INPUT_B';
export const TOGGLE_ADDER_6_OUTPUT_S = 'TOGGLE_ADDER_6_OUTPUT_S';
export const TOGGLE_ADDER_6_OUTPUT_S = 'TOGGLE_ADDER_6_OUTPUT_S';
// Adder 7
export const TOGGLE_ADDER_7_INPUT_B = 'TOGGLE_ADDER_7_INPUT_B';
export const TOGGLE_ADDER_7_INPUT_B = 'TOGGLE_ADDER_7_INPUT_B';
export const TOGGLE_ADDER_7_INPUT_B = 'TOGGLE_ADDER_7_INPUT_B';
export const TOGGLE_ADDER_7_OUTPUT_S = 'TOGGLE_ADDER_7_OUTPUT_S';
export const TOGGLE_ADDER_7_OUTPUT_S = 'TOGGLE_ADDER_7_OUTPUT_S';
// Operations value
export const TOGGLE_OPERATION_VALUE_0 = 'TOGGLE_OPERATION_VALUE_0';
export const TOGGLE_OPERATION_VALUE_1 = 'TOGGLE_OPERATION_VALUE_1';
export const TOGGLE_OPERATION_VALUE_2 = 'TOGGLE_OPERATION_VALUE_2';
export const TOGGLE_OPERATION_VALUE_3 = 'TOGGLE_OPERATION_VALUE_3';
