export const TOGGLE_REGISTER_A_VAR_0 = 'TOGGLE_REGISTER_A_VAR_0';
export const TOGGLE_REGISTER_A_VAR_1 = 'TOGGLE_REGISTER_A_VAR_1';
export const TOGGLE_REGISTER_A_VAR_2 = 'TOGGLE_REGISTER_A_VAR_2';
export const TOGGLE_REGISTER_A_VAR_3 = 'TOGGLE_REGISTER_A_VAR_3';
export const TOGGLE_REGISTER_A_VAR_4 = 'TOGGLE_REGISTER_A_VAR_4';
export const TOGGLE_REGISTER_A_VAR_5 = 'TOGGLE_REGISTER_A_VAR_5';
export const TOGGLE_REGISTER_A_VAR_6 = 'TOGGLE_REGISTER_A_VAR_6';
export const TOGGLE_REGISTER_A_VAR_7 = 'TOGGLE_REGISTER_A_VAR_7';

export const TOGGLE_REGISTER_B_VAR_0 = 'TOGGLE_REGISTER_B_VAR_0';
export const TOGGLE_REGISTER_B_VAR_1 = 'TOGGLE_REGISTER_B_VAR_1';
export const TOGGLE_REGISTER_B_VAR_2 = 'TOGGLE_REGISTER_B_VAR_2';
export const TOGGLE_REGISTER_B_VAR_3 = 'TOGGLE_REGISTER_B_VAR_3';
export const TOGGLE_REGISTER_B_VAR_4 = 'TOGGLE_REGISTER_B_VAR_4';
export const TOGGLE_REGISTER_B_VAR_5 = 'TOGGLE_REGISTER_B_VAR_5';
export const TOGGLE_REGISTER_B_VAR_6 = 'TOGGLE_REGISTER_B_VAR_6';
export const TOGGLE_REGISTER_B_VAR_7 = 'TOGGLE_REGISTER_B_VAR_7';

export const TOGGLE_REGISTER_C_VAR_0 = 'TOGGLE_REGISTER_C_VAR_0';
export const TOGGLE_REGISTER_C_VAR_1 = 'TOGGLE_REGISTER_C_VAR_1';
export const TOGGLE_REGISTER_C_VAR_2 = 'TOGGLE_REGISTER_C_VAR_2';
export const TOGGLE_REGISTER_C_VAR_3 = 'TOGGLE_REGISTER_C_VAR_3';
export const TOGGLE_REGISTER_C_VAR_4 = 'TOGGLE_REGISTER_C_VAR_4';
export const TOGGLE_REGISTER_C_VAR_5 = 'TOGGLE_REGISTER_C_VAR_5';
export const TOGGLE_REGISTER_C_VAR_6 = 'TOGGLE_REGISTER_C_VAR_6';
export const TOGGLE_REGISTER_C_VAR_7 = 'TOGGLE_REGISTER_C_VAR_7';

export const INIT_STAND = 'INIT_STAND';
